dist: trusty
sudo: required
group: deprecated-2017Q4

language: python3

services:
  - docker

git:
  depth: 3

before_install:
  - sudo apt-get update
  - sudo apt-get install -y gawk wget diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping curl dosfstools mtools parted syslinux tree docker-ce nodejs npm
  - sudo apt-cache policy git
  - sudo curl -sfL https://balena.io/install.sh | sh
  - sudo groupadd docker || true
  - sudo groupadd balena || true
  - sudo usermod -aG docker $USER || true
  - sudo usermod -aG balena $USER || true
  - sudo bash -c 'balenad&'
  - sudo service docker start
  - docker run hello-world
  - balena run hello-world


script:
  - ./resin-yocto-scripts/build/barys -r --shared-downloads $(pwd)/shared-downloads/ --shared-sstate $(pwd)/shared-sstate/ -m raspberrypi3


# deploy:
#   provider: releases
#   api_key: "GITHUB OAUTH TOKEN"
#   file: "FILE TO UPLOAD"
#   skip_cleanup: true
#   on:
#     tags: true